# DSV4 model/kernel canonical defaults and PEFT (OFT) defaults shared across
# the DSV4 launchers in examples/low_precision/. 

# === DSV4 model / canonical kernel defaults ===
export MEGATRON_DSV4_ATTN_IMPL="${MEGATRON_DSV4_ATTN_IMPL:-tilelang}"
export MEGATRON_USE_KV_QAT="${MEGATRON_USE_KV_QAT:-1}"
export MEGATRON_DSV4_TILE_ROUTER_STE_BACKWARD="${MEGATRON_DSV4_TILE_ROUTER_STE_BACKWARD:-1}"
export SGLANG_DSV4_DET_FP8_GEMM="${SGLANG_DSV4_DET_FP8_GEMM:-1}"
export MEGATRON_DSV4_DET_FP8_GEMM="${MEGATRON_DSV4_DET_FP8_GEMM:-${SGLANG_DSV4_DET_FP8_GEMM}}"
export SGLANG_DSV4_USE_TILEKERNELS="${SGLANG_DSV4_USE_TILEKERNELS:-1}"
export MEGATRON_DSV4_USE_TILEKERNELS="${MEGATRON_DSV4_USE_TILEKERNELS:-${SGLANG_DSV4_USE_TILEKERNELS}}"
export MEGATRON_DSV4_CKPT_VERSION="${MEGATRON_DSV4_CKPT_VERSION:-0415}"
export SGLANG_DSV4_GATE_LINEAR_IMPL="${SGLANG_DSV4_GATE_LINEAR_IMPL:-persistent}"
export MEGATRON_DSV4_GATE_LINEAR_IMPL="${MEGATRON_DSV4_GATE_LINEAR_IMPL:-${SGLANG_DSV4_GATE_LINEAR_IMPL}}"
export SGLANG_DSV4_FAST_MHC_PRE="${SGLANG_DSV4_FAST_MHC_PRE:-0}"
export SGLANG_DSV4_CANONICAL_RMSNORM="${SGLANG_DSV4_CANONICAL_RMSNORM:-1}"
export MEGATRON_DSV4_CANONICAL_RMSNORM="${MEGATRON_DSV4_CANONICAL_RMSNORM:-${SGLANG_DSV4_CANONICAL_RMSNORM}}"
export SGLANG_DSV4_CANONICAL_RMSNORM_IMPL="${SGLANG_DSV4_CANONICAL_RMSNORM_IMPL:-persistent}"
export MEGATRON_DSV4_CANONICAL_RMSNORM_IMPL="${MEGATRON_DSV4_CANONICAL_RMSNORM_IMPL:-${SGLANG_DSV4_CANONICAL_RMSNORM_IMPL}}"
export SGLANG_DSV4_CANONICAL_COMPRESSOR_LINEAR="${SGLANG_DSV4_CANONICAL_COMPRESSOR_LINEAR:-1}"
export MEGATRON_DSV4_CANONICAL_COMPRESSOR_LINEAR="${MEGATRON_DSV4_CANONICAL_COMPRESSOR_LINEAR:-${SGLANG_DSV4_CANONICAL_COMPRESSOR_LINEAR}}"
export SGLANG_DSV4_CANONICAL_COMPRESSOR_LINEAR_IMPL="${SGLANG_DSV4_CANONICAL_COMPRESSOR_LINEAR_IMPL:-fixed_order}"
export MEGATRON_DSV4_CANONICAL_COMPRESSOR_LINEAR_IMPL="${MEGATRON_DSV4_CANONICAL_COMPRESSOR_LINEAR_IMPL:-${SGLANG_DSV4_CANONICAL_COMPRESSOR_LINEAR_IMPL}}"
# Debug-parity launchers override SGLANG_DSV4_CANONICAL_LM_HEAD to 1 before
# sourcing this file; production launchers run with the default 0.
export SGLANG_DSV4_CANONICAL_LM_HEAD="${SGLANG_DSV4_CANONICAL_LM_HEAD:-0}"
export MEGATRON_DSV4_CANONICAL_LM_HEAD="${MEGATRON_DSV4_CANONICAL_LM_HEAD:-${SGLANG_DSV4_CANONICAL_LM_HEAD}}"
export SGLANG_DSV4_CANONICAL_LM_HEAD_IMPL="${SGLANG_DSV4_CANONICAL_LM_HEAD_IMPL:-persistent}"
export SGLANG_DSV4_CANONICAL_COMPRESS_TOPK_ORDER="${SGLANG_DSV4_CANONICAL_COMPRESS_TOPK_ORDER:-1}"
export MEGATRON_DSV4_CANONICAL_COMPRESS_TOPK_ORDER="${MEGATRON_DSV4_CANONICAL_COMPRESS_TOPK_ORDER:-${SGLANG_DSV4_CANONICAL_COMPRESS_TOPK_ORDER}}"
export SGLANG_DSV4_PREFILL_FIXED_WINDOW_LAYOUT="${SGLANG_DSV4_PREFILL_FIXED_WINDOW_LAYOUT:-1}"
export MEGATRON_DSV4_PREFILL_FIXED_WINDOW_LAYOUT="${MEGATRON_DSV4_PREFILL_FIXED_WINDOW_LAYOUT:-${SGLANG_DSV4_PREFILL_FIXED_WINDOW_LAYOUT}}"
export SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM="${SGLANG_BATCH_INVARIANT_OPS_ENABLE_MM_DEEPGEMM:-1}"

# === DeepEP single-node default ===
# DeepEP dispatch on a single node runs over intranode NVLink and does not need
# NCCL GIN (GPU-initiated networking / direct-RDMA kernels).
export EP_DISABLE_GIN="${EP_DISABLE_GIN:-1}"

# === PEFT (OFT) defaults shared across DSV4 launchers ===
export PEFT_METHOD="${PEFT_METHOD:-oft}"
export PEFT_VARIANT="${PEFT_VARIANT:-dsv4}"
# Naming API follow-up: audit whether this can become all-linear
export TARGET_MODULES="${TARGET_MODULES:-wq_a,wq_b,wkv,wo_a,wo_b,w1,w2,w3}"
# Debug-parity launchers override OFT_BLOCK_SIZE to 128 before sourcing.
export OFT_BLOCK_SIZE="${OFT_BLOCK_SIZE:-32}"
export OFT_EPS="${OFT_EPS:-6e-5}"

# === SGLang context length ===
export ROLLOUT_MAX_PROMPT_LEN="${ROLLOUT_MAX_PROMPT_LEN:-1024}"
export ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN:-1024}"
export ROLLOUT_MAX_CONTEXT_LEN="${ROLLOUT_MAX_CONTEXT_LEN:-$((ROLLOUT_MAX_PROMPT_LEN + ROLLOUT_MAX_RESPONSE_LEN))}"
export SGLANG_CONTEXT_LENGTH="${SGLANG_CONTEXT_LENGTH:-${ROLLOUT_MAX_CONTEXT_LEN}}"
