#!/usr/bin/env python3
"""Generate the pinned CUDA 12.8/H200 installation profile."""

from __future__ import annotations

import argparse
import hashlib
import os
import shlex
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Mapping, Sequence

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_OUTPUT = Path(__file__).with_name("pins.env")


class PinError(ValueError):
    """Raised when source manifests do not define one coherent stack."""


CU128_PROFILE = {
    "CUDA_PROFILE": "cu128",
    "CUDA_TOOLKIT_VERSION": "12.8",
    "PYTHON_VERSION": "3.12",
    "TORCH_INDEX_URL": "https://download.pytorch.org/whl/cu128",
    "FLASHINFER_INDEX_URL": "https://flashinfer.ai/whl/cu128",
    "SGLANG_WHEEL_INDEX_URL": "https://docs.sglang.ai/whl/cu128",
    "TORCHVISION_VERSION": "0.26.0",
    "TORCHAUDIO_VERSION": "2.11.0",
    "CUDA_PYTHON_VERSION": "12.9.2",
    "H200_COMPUTE_CAPABILITY": "9.0",
    "CUDNN_VERSION_POLICY": "torch-metadata",
    "NCCL_VERSION_POLICY": "torch-metadata",
    "APEX_SOURCE_URL": "https://github.com/NVIDIA/apex.git",
    "APEX_COMMIT": "f199212da7234bf9be2244cad5b9bfa2f5fe2675",
}


def read_toml(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def exact_requirement_version(requirements: Sequence[str], name: str) -> str:
    matches = [
        requirement
        for text in requirements
        if canonicalize_name((requirement := Requirement(text)).name) == canonicalize_name(name)
    ]
    if len(matches) != 1:
        raise PinError(f"{name}: expected one requirement, found {len(matches)}")
    exact = [spec.version for spec in matches[0].specifier if spec.operator == "=="]
    if len(exact) != 1:
        raise PinError(f"{name}: expected one exact == version")
    return exact[0]


def require_matching_ref(uv_source: dict, release_pin: dict, name: str) -> str:
    uv_ref = uv_source.get("rev")
    tested_ref = release_pin.get("tested-ref")
    if uv_ref != tested_ref:
        raise PinError(f"{name}: tool.uv.sources rev {uv_ref!r} != tested-ref {tested_ref!r}")
    if not isinstance(tested_ref, str) or not tested_ref:
        raise PinError(f"{name}: missing tested-ref")
    return tested_ref


def collect_pins(repo_root: Path, sglang_root: Path) -> dict[str, str]:
    orbit = read_toml(repo_root / "pyproject.toml")
    sglang = read_toml(sglang_root / "python" / "pyproject.toml")

    project = orbit["project"]
    uv_sources = orbit["tool"]["uv"]["sources"]
    release_pins = orbit["tool"]["orbit"]["release"]["backend-pins"]
    sglang_requirements = sglang["project"]["dependencies"]

    pins = dict(CU128_PROFILE)
    pins.update(
        {
            "ORBIT_VERSION": str(project["version"]),
            "TORCH_VERSION": exact_requirement_version(sglang_requirements, "torch"),
            "FLASHINFER_VERSION": exact_requirement_version(sglang_requirements, "flashinfer-python"),
            "TRANSFORMERS_VERSION": exact_requirement_version(project["dependencies"], "transformers"),
            "SGLANG_SOURCE_URL": str(release_pins["sglang"]["source"]),
            "SGLANG_COMMIT": require_matching_ref(
                uv_sources["sglang"], release_pins["sglang"], "sglang"
            ),
            "MEGATRON_SOURCE_URL": str(release_pins["megatron-core"]["source"]),
            "MEGATRON_COMMIT": require_matching_ref(
                uv_sources["megatron-core"], release_pins["megatron-core"], "megatron-core"
            ),
            "MEGATRON_BRIDGE_SOURCE_URL": str(release_pins["megatron-bridge"]["source"]),
            "MEGATRON_BRIDGE_COMMIT": require_matching_ref(
                uv_sources["megatron-bridge"],
                release_pins["megatron-bridge"],
                "megatron-bridge",
            ),
            "TRANSFORMER_ENGINE_SOURCE_URL": str(uv_sources["transformer-engine"]["git"]),
            "TRANSFORMER_ENGINE_COMMIT": str(uv_sources["transformer-engine"]["rev"]),
        }
    )
    return pins


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_pins(pins: Mapping[str, str], source_hashes: Mapping[str, str]) -> str:
    lines = [
        "# scripts/slurm/setup/cu128/pins.env",
        "# AUTO-GENERATED by extract_pins.py --write; do not edit by hand.",
        "# Extracted values come from Orbit and pinned SGLang manifests.",
        "# CUDA 12.8/H200 profile values are hand-owned in CU128_PROFILE.",
        "#",
    ]
    for source, digest in sorted(source_hashes.items()):
        lines.append(f"# source_sha256 {source} {digest}")
    lines.append("")
    for key in sorted(pins):
        value = str(pins[key])
        if "\n" in value or "\r" in value:
            raise PinError(f"{key}: pin values must be single-line")
        lines.append(f"{key}={shlex.quote(value)}")
    return "\n".join(lines) + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as stream:
            temporary = Path(stream.name)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def run_check(path: Path, expected: str) -> int:
    if not path.exists():
        print(f"{path}: pins.env is missing", file=sys.stderr)
        return 1
    observed = path.read_text()
    if observed == expected:
        return 0
    print(f"{path}: pins.env is stale; run extract_pins.py --write", file=sys.stderr)
    return 1


def default_workspace(repo_root: Path) -> Path:
    explicit = os.environ.get("ORBIT_WORKSPACE")
    if explicit:
        return Path(explicit).expanduser().resolve()
    try:
        common = subprocess.run(
            [
                "git",
                "-C",
                str(repo_root),
                "rev-parse",
                "--path-format=absolute",
                "--git-common-dir",
            ],
            check=True,
            text=True,
            capture_output=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as error:
        raise PinError(f"cannot resolve Orbit Git common directory: {error}") from error
    common_path = Path(common).resolve()
    canonical_repo = common_path.parent if common_path.name == ".git" else repo_root.resolve()
    return canonical_repo.parent


def generated_content(repo_root: Path, sglang_root: Path) -> str:
    orbit_manifest = repo_root / "pyproject.toml"
    sglang_manifest = sglang_root / "python" / "pyproject.toml"
    pins = collect_pins(repo_root, sglang_root)
    hashes = {
        "pyproject.toml": file_sha256(orbit_manifest),
        "sglang/python/pyproject.toml": file_sha256(sglang_manifest),
    }
    return render_pins(pins, hashes)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="atomically regenerate pins.env")
    mode.add_argument("--check", action="store_true", help="fail if pins.env is stale")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--sglang-root", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    repo_root = args.repo_root.expanduser().resolve()
    sglang_root = (
        args.sglang_root.expanduser().resolve()
        if args.sglang_root
        else default_workspace(repo_root) / "sglang"
    )
    try:
        content = generated_content(repo_root, sglang_root)
    except (KeyError, OSError, PinError, tomllib.TOMLDecodeError) as error:
        print(f"extract_pins.py: {error}", file=sys.stderr)
        return 1
    if args.write:
        write_atomic(args.output, content)
        print(f"wrote {args.output}")
        return 0
    return run_check(args.output, content)


if __name__ == "__main__":
    raise SystemExit(main())
