#!/usr/bin/env python3
"""Audit an Orbit CUDA 12.8 environment against generated installation pins."""

from __future__ import annotations

import argparse
import importlib
import importlib.metadata as metadata
import json
import re
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Mapping, Sequence
from urllib.parse import unquote, urlparse

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_PINS = Path(__file__).with_name("pins.env")
PACKAGE_VERSION_SPECS = (
    ("orbit", "orbit version", ("ORBIT_VERSION",), "source"),
    ("torch", "torch build", ("TORCH_VERSION",), "cuda-local"),
    ("torchvision", "torchvision build", ("TORCHVISION_VERSION",), "cuda-local"),
    ("torchaudio", "torchaudio build", ("TORCHAUDIO_VERSION",), "cuda-local"),
    (
        "flashinfer-python",
        "flashinfer-python version",
        ("FLASHINFER_VERSION", "FLASHINFER_PYTHON_VERSION"),
        "exact",
    ),
    (
        "flashinfer-cubin",
        "flashinfer-cubin version",
        ("FLASHINFER_CUBIN_VERSION",),
        "exact",
    ),
    ("transformers", "transformers version", ("TRANSFORMERS_VERSION",), "exact"),
    ("cuda-python", "cuda-python version", ("CUDA_PYTHON_VERSION",), "exact"),
    ("sglang", "sglang version", ("SGLANG_VERSION",), "source"),
    (
        "transformer-engine",
        "transformer-engine version",
        ("TRANSFORMER_ENGINE_VERSION",),
        "source",
    ),
)


class VerificationError(RuntimeError):
    """Raised when verifier inputs are malformed."""


@dataclass(frozen=True)
class Check:
    label: str
    ok: bool
    detail: str = ""


def load_pins(path: Path) -> dict[str, str]:
    """Load the simple shell assignments generated by extract_pins.py."""
    pins: dict[str, str] = {}
    assignment = re.compile(r"^([A-Z][A-Z0-9_]*)=(.*)$")
    for line_number, raw_line in enumerate(path.read_text().splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = assignment.fullmatch(line)
        if match is None:
            raise VerificationError(f"{path}:{line_number}: invalid pin assignment")
        key, encoded = match.groups()
        values = shlex.split(encoded, comments=False, posix=True)
        if len(values) != 1:
            raise VerificationError(f"{path}:{line_number}: expected one shell value")
        pins[key] = values[0]
    return pins


def check_versions(pins: Mapping[str, str], installed: Mapping[str, str]) -> list[Check]:
    """Audit every supported package version represented by the generated pins."""
    checks: list[Check] = []
    for distribution, label, pin_names, comparison in PACKAGE_VERSION_SPECS:
        pin_name = next((name for name in pin_names if pins.get(name)), None)
        required = distribution in {"torch", "torchvision", "torchaudio"}
        if pin_name is None and not required:
            continue
        if pin_name is None:
            checks.append(Check(label, False, f"missing {pin_names[0]} in pins"))
            continue

        expected = pins[pin_name]
        observed = installed.get(distribution)
        if comparison == "cuda-local":
            expected_installed = f"{expected}+{pins.get('CUDA_PROFILE', 'cu128')}"
            ok = observed == expected_installed
        elif comparison == "source":
            expected_installed = expected
            ok = observed == expected or bool(observed and observed.startswith(f"{expected}+"))
        else:
            expected_installed = expected
            ok = observed == expected

        if ok:
            detail = observed or expected_installed
        else:
            detail = f"expected {expected_installed}, got {observed or 'not installed'}"
        checks.append(Check(label, ok, detail))
    return checks


def _direct_url_path(record: Mapping[str, object]) -> Path | None:
    url = record.get("url")
    if not isinstance(url, str):
        return None
    parsed = urlparse(url)
    if parsed.scheme != "file":
        return None
    return Path(unquote(parsed.path)).resolve()


def check_editables(
    expected_paths: Mapping[str, Path],
    direct_urls: Mapping[str, Mapping[str, object] | None],
) -> list[Check]:
    """Require each distribution to be editable from its exact source checkout."""
    checks: list[Check] = []
    for distribution, expected in expected_paths.items():
        label = f"{distribution} editable source"
        record = direct_urls.get(distribution)
        if record is None:
            checks.append(Check(label, False, "direct_url.json is missing"))
            continue
        directory_info = record.get("dir_info")
        editable = isinstance(directory_info, dict) and directory_info.get("editable") is True
        observed = _direct_url_path(record)
        expected_resolved = expected.resolve()
        if not editable:
            checks.append(Check(label, False, "installation is not editable"))
        elif observed != expected_resolved:
            checks.append(Check(label, False, f"expected {expected_resolved}, got {observed}"))
        else:
            checks.append(Check(label, True, str(observed)))
    return checks


def _git_head(path: Path) -> str:
    return subprocess.run(
        ["git", "-C", str(path), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _git_dirty(path: Path) -> bool:
    output = subprocess.run(
        ["git", "-C", str(path), "status", "--porcelain"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return bool(output.strip())


def check_sources(
    source_paths: Mapping[str, Path],
    expected_commits: Mapping[str, str | None],
    *,
    git_head: Callable[[Path], str] = _git_head,
    git_dirty: Callable[[Path], bool] = _git_dirty,
) -> list[Check]:
    """Audit immutable source commits and reject uncommitted source changes."""
    checks: list[Check] = []
    for name, path in source_paths.items():
        label = f"{name} source revision"
        expected = expected_commits.get(name)
        if expected is None:
            checks.append(Check(label, False, "expected commit is missing from pins"))
            continue
        if not path.is_dir():
            checks.append(Check(label, False, f"source checkout is missing: {path}"))
            continue
        try:
            observed = git_head(path)
            dirty = git_dirty(path)
        except (OSError, subprocess.CalledProcessError) as error:
            checks.append(Check(label, False, f"cannot inspect {path}: {error}"))
            continue
        if observed != expected:
            checks.append(Check(label, False, f"expected {expected}, got {observed}"))
        elif dirty:
            checks.append(Check(label, False, f"{path} has uncommitted changes"))
        else:
            checks.append(Check(label, True, observed))
    return checks


def check_source_clean(
    name: str,
    path: Path,
    *,
    git_dirty: Callable[[Path], bool] = _git_dirty,
) -> Check:
    """Check a mutable editable checkout without creating a self-referential pin."""
    label = f"{name} source cleanliness"
    if not path.is_dir():
        return Check(label, False, f"source checkout is missing: {path}")
    try:
        dirty = git_dirty(path)
    except (OSError, subprocess.CalledProcessError) as error:
        return Check(label, False, f"cannot inspect {path}: {error}")
    if dirty:
        return Check(label, False, f"{path} has uncommitted changes")
    return Check(label, True, str(path.resolve()))


def check_import(
    module_name: str,
    *,
    importer: Callable[[str], object] = importlib.import_module,
) -> Check:
    """Import a module and ensure it resolves to a concrete installed file."""
    label = f"import {module_name}"
    try:
        module = importer(module_name)
    except Exception as error:  # Import-time extension errors are audit results.
        return Check(label, False, f"{type(error).__name__}: {error}")
    module_file = getattr(module, "__file__", None)
    if not module_file:
        return Check(label, False, "resolved as namespace package without __file__")
    return Check(label, True, str(Path(module_file).resolve()))


def print_summary(checks: Sequence[Check]) -> int:
    """Print labeled results and return the number of failed checks."""
    failures = 0
    for check in checks:
        status = "PASS" if check.ok else "FAIL"
        if not check.ok:
            failures += 1
        suffix = f": {check.detail}" if check.detail else ""
        print(f"[{status}] {check.label}{suffix}")
    print(f"{len(checks) - failures} passed, {failures} failed")
    return failures


def _installed_version(distribution: str) -> str | None:
    try:
        return metadata.version(distribution)
    except metadata.PackageNotFoundError:
        return None


def _direct_url(distribution: str) -> Mapping[str, object] | None:
    try:
        raw = metadata.distribution(distribution).read_text("direct_url.json")
    except metadata.PackageNotFoundError:
        return None
    if raw is None:
        return None
    parsed = json.loads(raw)
    if not isinstance(parsed, dict):
        raise VerificationError(f"{distribution} direct_url.json is not an object")
    return parsed


def default_workspace(repo_root: Path = REPO_ROOT) -> Path:
    """Return miles-orbit even when this script runs from a linked worktree."""
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "--git-common-dir"],
        check=True,
        capture_output=True,
        text=True,
    )
    common_dir = Path(result.stdout.strip())
    if not common_dir.is_absolute():
        common_dir = repo_root / common_dir
    return common_dir.resolve().parent.parent


def _pin(pins: Mapping[str, str], *names: str) -> str | None:
    for name in names:
        value = pins.get(name)
        if value:
            return value
    return None


def source_revision_inputs(
    pins: Mapping[str, str], workspace: Path
) -> tuple[dict[str, Path], dict[str, str | None]]:
    """Return only immutable external checkouts; Orbit cannot pin its own HEAD."""
    source_paths = {
        "sglang": workspace / "sglang",
        "megatron-lm": workspace / "Megatron-LM",
        "megatron-bridge": workspace / "Megatron-Bridge",
        "transformer-engine": workspace / "TransformerEngine",
    }
    expected_commits = {
        "sglang": _pin(pins, "SGLANG_COMMIT", "SGLANG_GIT_COMMIT"),
        "megatron-lm": _pin(pins, "MEGATRON_LM_COMMIT", "MEGATRON_COMMIT"),
        "megatron-bridge": _pin(pins, "MEGATRON_BRIDGE_COMMIT"),
        "transformer-engine": _pin(
            pins, "TRANSFORMER_ENGINE_COMMIT", "TRANSFORMER_ENGINE_GIT_COMMIT"
        ),
    }
    return source_paths, expected_commits


def metadata_checks(pins: Mapping[str, str], orbit_root: Path, workspace: Path) -> list[Check]:
    """Build the deterministic, GPU-free audit check set."""
    installed = {name: _installed_version(name) for name, _, _, _ in PACKAGE_VERSION_SPECS}
    checks = check_versions(pins, installed)

    editable_paths = {
        "orbit": orbit_root,
        "sglang": workspace / "sglang" / "python",
        "megatron-core": workspace / "Megatron-LM",
        "megatron-bridge": workspace / "Megatron-Bridge",
    }
    checks.extend(
        check_editables(editable_paths, {name: _direct_url(name) for name in editable_paths})
    )

    checks.append(check_source_clean("orbit", orbit_root))
    source_paths, expected_commits = source_revision_inputs(pins, workspace)
    checks.extend(check_sources(source_paths, expected_commits))

    for module_name in (
        "torch",
        "torchvision",
        "torchaudio",
        "orbit",
        "sglang",
        "megatron.core",
        "megatron.bridge",
        "transformer_engine",
        "flashinfer",
        "apex",
    ):
        checks.append(check_import(module_name))
    return checks


def _bf16_matmul_probe(torch_module: object) -> bool:
    left = torch_module.randn((512, 512), device="cuda", dtype=torch_module.bfloat16)
    right = torch_module.randn((512, 512), device="cuda", dtype=torch_module.bfloat16)
    result = left @ right
    torch_module.cuda.synchronize()
    return bool(torch_module.isfinite(result).all().item())


def _format_library_version(value: object) -> str:
    if isinstance(value, tuple):
        return ".".join(str(part) for part in value)
    return str(value)


def check_h200_runtime(
    pins: Mapping[str, str],
    *,
    torch_module: object | None = None,
    matmul_probe: Callable[[object], bool] = _bf16_matmul_probe,
) -> list[Check]:
    """Run GPU checks that must execute inside the target H200 allocation."""
    if torch_module is None:
        try:
            torch_module = importlib.import_module("torch")
        except Exception as error:
            return [Check("H200 runtime", False, f"cannot import torch: {error}")]

    cuda = getattr(torch_module, "cuda", None)
    if cuda is None or not cuda.is_available():
        return [Check("CUDA availability", False, "torch.cuda.is_available() is false")]

    checks: list[Check] = []
    try:
        device_name = cuda.get_device_name(0)
        capability = cuda.get_device_capability(0)
        capability_text = f"{capability[0]}.{capability[1]}"
        expected_capability = pins.get("H200_COMPUTE_CAPABILITY", "9.0")
        cuda_runtime = getattr(getattr(torch_module, "version", None), "cuda", None)
        expected_cuda = pins.get("CUDA_TOOLKIT_VERSION", "12.8")
        bf16_supported = bool(cuda.is_bf16_supported())
        cudnn_version = torch_module.backends.cudnn.version()
        nccl_version = cuda.nccl.version()
    except Exception as error:
        return [Check("H200 runtime metadata", False, f"{type(error).__name__}: {error}")]

    checks.extend(
        [
            Check("H200 device", "H200" in device_name, device_name),
            Check(
                "CUDA runtime",
                cuda_runtime == expected_cuda,
                str(cuda_runtime)
                if cuda_runtime == expected_cuda
                else f"expected {expected_cuda}, got {cuda_runtime}",
            ),
            Check(
                "Hopper compute capability",
                capability_text == expected_capability,
                capability_text
                if capability_text == expected_capability
                else f"expected {expected_capability}, got {capability_text}",
            ),
            Check("BF16 support", bf16_supported, str(bf16_supported)),
            Check(
                "cuDNN runtime",
                bool(cudnn_version),
                _format_library_version(cudnn_version),
            ),
            Check(
                "NCCL runtime",
                bool(nccl_version),
                _format_library_version(nccl_version),
            ),
        ]
    )
    try:
        matmul_ok = matmul_probe(torch_module)
        checks.append(Check("BF16 CUDA matmul", matmul_ok, "finite 512x512 result"))
    except Exception as error:
        checks.append(Check("BF16 CUDA matmul", False, f"{type(error).__name__}: {error}"))
    return checks


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pins", type=Path, default=DEFAULT_PINS)
    parser.add_argument("--orbit-root", type=Path, default=REPO_ROOT)
    source_group = parser.add_mutually_exclusive_group()
    source_group.add_argument("--source-root", type=Path)
    source_group.add_argument("--workspace", dest="source_root", type=Path, help=argparse.SUPPRESS)
    parser.add_argument(
        "--full-h200",
        action="store_true",
        help="also run CUDA/H200/BF16/cuDNN/NCCL checks on a compute node",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    source_root = args.source_root or default_workspace(args.orbit_root)
    try:
        pins = load_pins(args.pins)
        checks = metadata_checks(pins, args.orbit_root.resolve(), source_root.resolve())
        if args.full_h200:
            checks.extend(check_h200_runtime(pins))
    except (OSError, VerificationError, subprocess.CalledProcessError, json.JSONDecodeError) as error:
        print(f"verification input error: {error}", file=sys.stderr)
        return 2
    return 1 if print_summary(checks) else 0


if __name__ == "__main__":
    raise SystemExit(main())
