#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

MODEL_ARGS_NUM_LAYERS=${MODEL_ARGS_NUM_LAYERS:-6}
MODEL_ARGS_FIRST_K_DENSE_REPLACE=${MODEL_ARGS_FIRST_K_DENSE_REPLACE:-1}
MODEL_ARGS_MOE_LAYER_FREQ=${MODEL_ARGS_MOE_LAYER_FREQ:-"[0,1,1,1,1,1]"}

source "${SCRIPT_DIR}/kimi-k25.sh"
